language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

sudo: false

env:
  global:
    - DEFAULT=1
    - PHPCS=1

matrix:
  fast_finish: true
  include:
    - php: 7.4snaphot
      env: CODECOVERAGE=1
    - php: 7.3
      env: CODECOVERAGE=1
    - php: 7.2
      env: CODECOVERAGE=1

install:
  - composer install --prefer-dist --no-interaction

before_script:
  - phpenv rehash
  - set +H

script:
  - |
    if [[ $TRAVIS_PHP_VERSION == '7.2' ]]; then
      # This is necessary to skip memory usage tests
      CODECOVERAGE=1 vendor/bin/phpunit --coverage-clover=clover.xml
    else
      vendor/bin/phpunit
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
